### Get All categories
GET http://localhost:3000/api/categories
X-API-key:RAHASIA
Accept: application/json

### Get category by ud
GET http://localhost:3000/api/categories/3
X-API-key:RAHASIA
Accept: application/json

### Create new categories
POST http://localhost:3000/api/categories
X-API-key:RAHASIA
Accept: application/json
Content-Type: application/json

{
    "name": "Computer"
}

### Update categories
PUT http://localhost:3000/api/categories/1
X-API-key:RAHASIA
Accept: application/json
Content-Type: application/json

{
    "name": "Handphone"
}

### Delete categories
DELETE  http://localhost:3000/api/categories/1
X-API-key:RAHASIA
Accept: application/json
Content-Type: application/json